version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 18.19.1
        - nvm use 18.19.1
        - node -v # Check Node.js version
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
